---
title: "Untitled"
format: html
editor: visual
---

::: panel-tabset

## Mapa animado

```{r, warning=FALSE, message=FALSE}

library(pacman)
library(lubridate)
library(gganimate)
library(ggthemes)

pacman::p_load(tidyverse, rnaturalearth, rnaturalearthdata, sf, 
               raster, reticulate,  maptools,maps,maptiles,gridExtra,
               ggspatial,rgeos, tmap,grid, rgbif, ggmap,
               rgrass7, sp, mapr, rgdal, RColorBrewer,ggrepel, leaflet)
```

```{r}
Honduras <- ne_countries(scale = "medium", 
                              returnclass = "sf", 
                              country = "Honduras")
```


```{r}
SETCHR <- read_delim("data/ebd_HN_gchwar_201701_201912_smp_relAug-2023.txt")
```
```{r}
head(SETCHR)
```


```{r}
SETCHR1 <- SETCHR %>%
  rename("Observaciones" = `OBSERVATION COUNT`,
         "Fecha" = `OBSERVATION DATE`) %>% 
  mutate(Observaciones = as.numeric(Observaciones)) %>% 
  filter(Observaciones < 5) %>%
  mutate(Year = year(Fecha)) %>% 
  filter(Year == "2018" | Year == "2019") %>% 
  dplyr::select(Year, Fecha, Observaciones, LONGITUDE, LATITUDE)
```

```{r}
head(SETCHR1)
```

```{r}
gg  <- ggplot()+
  geom_sf(data= Honduras)+
  geom_point(data =SETCHR1,  aes(x=LONGITUDE, y=LATITUDE,color= Observaciones),
             alpha= 0.3, size= 1, shape= 15)+
   transition_time(time = Fecha)+
  scale_color_gradient(low = "orange", high = "red", na.value = NA)+
  labs(title= "Abundancia de",
       subtitle = "Setophaga chrysoparia",
       color = "Abundancia")+
  theme_void()+
  theme(plot.title = element_text(size = 14))+
  theme(plot.subtitle = element_text(face= "italic", size = 12))
```


gganimate::animate(gg + ease_aes('cubic-in-out'), 
                   fps = 7, width = 600, height = 600, 
                   renderer = gifski_renderer())

## Mapa distribucion potencial

```{r}
library(SSDM)
```

```{r}
output_path <- "data/"

HN_clim.current <- geodata::worldclim_country("HN", var = "bio", path = output_path)

HN_clim.current_raster <- as(HN_clim.current, "Raster")
```

```{r}
sdrf <- modelling(algorithm = 'RF', 
                  Env = HN_clim.current_raster, 
                  Occurrences = SETCHR1,
                  Xcol = 'LONGITUDE', 
                  Ycol = 'LATITUDE', 
                  metric = 'TSS', 
                  select.metric = 'AUC',
                  cv = "holdout",
                  cv.param = c(0.7, 2),
                  thresh = 1001,
                  select.thresh = c(0.75))
```

```{r}
plot(sdrf)
```


:::
